name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Build
      run: export SCULPTOR_IGNORE_SUDO_CHECK=true; php sculptor-cli app:build --build-version=${{ steps.get_tag.outputs.VERSION }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.VERSION }}
        release_name: Release ${{ steps.get_tag.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload sculptor-cli asset
      id: upload-release-asset-sculptor-cli
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builds/sculptor-cli
        asset_name: sculptor-cli
        asset_content_type: application/octet-stream
